KEYWORDS = [
    'UWS',
    'upper west side',
    'ues',
    'upper east side',
    'Lenox Hill'
    'Chelsea',
    'Hells Kitchen',
    'HK',
    'Two Bridges',
    'Tribeca',
    'LES',
    'Flatiron District',
    'Lower East Side',
    'East Village',
    'West Village',
    'midtown',
    'Chinatown',
    'Bowery',
    'fidi',
    'financial district',
    'Gramercy',
    'Greenwich',
    'alphabet city',
    'kips bay',
    'murray hill',
    'little Italy',
    'NoHo',
    'NoLita',
    'SoHo',
    'Stuyvesant Town',
    'stuy town',
    'stuytown',
    'Sutton Place',
    'Union Square',
    'Clinton',
    'Roosevelt Island'
###### BROOKLYN ######
    'barclays',
    'dumbo',
    'brooklyn public library',
    'park slope',
    'prospect park',
        #franklin ave is in crown heights
    'Franklin Ave',
    'Crown Heights',
    'barclays',
    'clinton hill',
    'Prospect Heights'
    'Brooklyn Heights',
    'Cobble Hill',
    'Boerum Hill',
    'Gowanus',
    'Vinegar Hill',
    'Fort Greene',
###### QUEENS  ######
    'astoria',
    'lic',
    'long island city'
###### RANDOM ######
    'month-to-month',
    'month to month',
    'm2m',
    'fully furnish',
    'fully furnished',
    'comes with furniture'
]