KEYWORDS = [
            'UWS',
            'upper west side',
            'Chelsea',
            'Hells Kitchen',
            'HK',
            'Two Bridges',
            'Tribeca',
            'LES',
            'Lower East Side',
            'East Village',
            'West Village',
            'midtown',
            'Chinatown',
            'Bowery',
            'fidi',
            'financial district',
            'Gramercy',
            'Greenwich',
            'alphabet city',
            'kips bay',
            'murray hill',
            'little Italy',
            'NoHo',
            'NoLita',
            'SoHo',
            'Stuyvesant Town',
            'stuy town',
            'Sutton Place',
            'Union Square',
            'barclays',
            'dumbo',
            'month-to-month',
            'month to month',
            'm2m',
            'brooklyn public library'
]